[package]
name = "demon"
version = "0.1.0"
authors = ["rdigua <digua@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.6"
dirs = "3.0.1"
# rusqlite="0.23.1"
[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]